### ISSUE TITLE
The plugin is not loaded by BungeeCord.

### ISSUE THREAD

**Issue by Lice2** [Meiallu/LuTags#1]
The plugin is not loaded by BungeeCord.

`00:45:06 [WARNING] Error loading plugin LuTags
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    ... 13 more
`
i use openjdk java21.
Or is it only for servers and not for proxy servers?
Greetings Lice

**Comment by Meiallu** [comment]
It's only for proxy servers, Lice. Just put the plugin on the same database on every server and it will work perfectly.

**Comment by Lice2** [comment]
ok thank you !
